### ISSUE TITLE
Error with Splash in Xamarin Studio

### ISSUE THREAD

**Issue by rasmuschristensen** [jimbobbennett/MvvmCross.XSAddIn#3]
I've installed the add-in in the latest stable Xamarin Studio. When I create a new Forms project based on the add-in, I keep getting this error, Is there a fix some how?
![screen shot 2016-08-19 at 14 48 43](https://cloud.githubusercontent.com/assets/1743614/17810292/8ca67da8-661c-11e6-8a42-27becbc9656f.png)

**Comment by jimbobbennett** [comment]
Sorry - only just seen this issue! Github did't send me a notification. Will get a fix in ASAP.

**Comment by jimbobbennett** [comment]
Now fixed in source - just publishing to the add-ins now.

**Comment by rasmuschristensen** [comment]
Great, cool templates!
