### ISSUE TITLE
Fails to install on Visual Studio for Mac

### ISSUE THREAD

**Issue by seank-com** [jimbobbennett/MvvmCross.XSAddIn#8]
Repro Steps

1. Launch Visual Studio for Mac
2. Select Visual Studio Community | Extensions from the menu
3. Select Gallery tab
4. enter MVVMCross in search box
5. Select MvvmCross Template Pack
6. Press Install...

See the following message

![screen shot 2017-07-17 at 3 29 13 pm](https://user-images.githubusercontent.com/1326518/28292902-327d9cd6-6b06-11e7-8ef6-0092cb75258b.png)

Warnings cause extension to not load

**Comment by jimbobbennett** [comment]
Ah - my fault for building with the beta of VS for Mac. Fixed with 1.4.12.
